export const SOCIAL_ICONS = [
  {
    key: "telegram",
    src: "telegram.svg",
    hoverSrc: "telegram-blue.svg",
    label: "Telegram account",
    details: "https://t.me/Rahulencoded",
    link: "https://t.me/Rahulencoded",
  },
  {
    key: "x",
    src: "X.svg",
    hoverSrc: "X-blue.svg",
    label: "X account",
    details: "https://x.com/Rahulencoded",
    link: "https://x.com/Rahulencoded",
  },
  {
    key: "world",
    src: "world.svg",
    hoverSrc: "world-blue.svg",
    label: "Pump.fun token Website",
    details: "https://pump.fun",
    link: "https://pump.fun",
  },
  {
    key: "search",
    src: "search.svg",
    hoverSrc: "search-blue.svg",
    label: "X Search",
    details: "https://x.com/search",
    link: "https://x.com/search",
  },
  {
    key: "pin",
    src: "pin.svg",
    hoverSrc: "pin-blue.svg",
    label: "Pump.fun chart",
    details: "https://pump.fun",
    link: "https://pump.fun",
  },
  {
    key: "feather",
    src: "/feather-blue.svg",
    hoverSrc: "/feather-blue.svg",
    label: "Latest tweet",
    details: "https://x.com/Rahulencoded",
    link: "https://x.com/Rahulencoded",
  },
] as const;
